// Module included in the following assemblies:
//
// * networking/hardware_networks/about-sriov.adoc

[id="supported-devices_{context}"]
= Supported devices

{product-title} supports the following network interface controller (NIC) models:

// What information do we need to include here? 
// Manufacturer, Model Number, vendor ID, device ID
// But there are two device IDs: PF device ID (physical device) and VF device ID (virtual device).
// Which one is assumed below?

//* Broadcom BCM57414 50GbE with vendor ID `xxx` and device ID `yyy`
//* Broadcom BCM75508 XXX with vendor ID `xxx` and device ID `yyy`
* Intel X710 10GbE SFP+ with vendor ID `0x8086` and device ID `0x1572`
* Intel XL710 40GbE SFP+ with vendor ID `0x8086` and device ID `0x1583`
* Intel XXV710 25GbE SFP28 with vendor ID `0x8086` and device ID `0x158b`
* Intel E810-CQDA2 100GbE dual-port QSPF28 and E810-2CQDA2 100GbE dual-port QSPF28 with vendor ID `0x8086` and device ID `0x1592`
* Intel E810-XXVDA2 25GbE dual-port SPF28 with vendor ID `0x8086` and device ID `0x159b`
* Intel E810-XXVDA4 25GbE quad-port SPF28 with vendor ID `0x8086` and device ID `0x1593`
* Mellanox MT27710 Family [ConnectX-4 Lx] 25GbE dual-port SFP28 with vendor ID `0x15b3` and device ID `0x1015`
* Mellanox MT27800 Family [ConnectX-5] 25GbE dual-port SFP28 with vendor ID `0x15b3` and device ID `0x1017`
* Mellanox MT27800 Family [ConnectX-5] 100GbE with vendor ID `0x15b3` and device ID `0x1017`
* Mellanox MT27700 Family [ConnectX-4] VPI adapter card, EDR IB (100Gb/s), single-port QSFP28 with vendor ID `0x15b3` and device ID `0x1013`
* Mellanox MT27800 Family [ConnectX-5] VPI adapter card, EDR IB (100Gb/s), single-port QSFP28 with vendor ID `0x15b3` and device ID `0x1017`
* Mellanox MT28880 Family [ConnectX-5 Ex] Ethernet controller, 100Gb/s, dual-port QSPF28 with vendor ID `0x15b3` and device ID `0x1019`
* Mellanox MT28908 Family [ConnectX-6] VPI adapter card, 100Gb/s (HDR100, EDR IB), single-port QSFP56 with vendor ID `0x15b3` and device ID `0x101b`
* Mellanox MT28908 Family [ConnectX-6] VPI adapter card, HDR200 IB (200Gb/s), single-port QSFP56 with vendor ID `0x15b3` and device ID `0x101b`
//* Pensando DSC-25 25GbE with vendor ID `0x1dd8` and device ID `0x1002`
//* Pensando DSC-100 100GbE with vendor ID `0x1dd8` and device ID `0x1003`
//* Silicom P410G8TS81 STS2 with vendor ID `0x8086`and device ID `xxx` 
//* Silicom P425G410G8TS81 STS4 vendor ID `0x8086`and device ID `xxx` 